<a href="https://colab.research.google.com/github/SHermukhammadjon/Data_Science_Zero_to_Mastery/blob/main/ML/scikit_learn4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Maschine Learning Loyiha qadamalri
(4-notebook)

<img src="https://drive.google.com/uc?id=1ZKgMJ92OMgfBHsvQmFmNhXw5aM9P9vXu">

In [1]:
import pandas as pd
import numpy as np
import sklearn

## 4-QADAM. Machine Learning
### 26.05.2023
### Load the dataset

In [2]:
dataset = pd.read_csv("https://github.com/ageron/handson-ml2/blob/master/datasets/housing/housing.csv?raw=true")
dataset 

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

### Split the dataset

In [3]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(dataset, test_size = 0.2, random_state=31)

x_train = train_set.drop('median_house_value', axis = 1)
y = train_set['median_house_value'].copy()

x_num = x_train.drop('ocean_proximity', axis = 1)

In [4]:
x_train

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7083     -118.01     33.93                31.0       3395.0           742.0   
747      -122.09     37.66                40.0       1340.0           313.0   
19922    -119.35     36.32                10.0       3817.0           719.0   
449      -122.28     37.87                46.0       1777.0           446.0   
11808    -121.11     38.91                24.0       2558.0           423.0   
...          ...       ...                 ...          ...             ...   
604      -122.08     37.69                36.0       2350.0           499.0   
28       -122.28     37.84                50.0       2082.0           492.0   
826      -122.09     37.63                36.0       1570.0           274.0   
3735     -118.40     34.19                35.0       1631.0           356.0   
14946    -116.98     32.72                15.0       4209.0           680.0   

       population  households  median_income ocean_proximity  
7083       1886.0       737.0         4.4118       <1H OCEAN  
747         766.0       271.0         3.4722        NEAR BAY  
19922      1686.0       714.0         3.8235          INLAND  
449         805.0       431.0         2.8676        NEAR BAY  
11808      1149.0       403.0         4.0679          INLAND  
...           ...         ...            ...             ...  
604        1105.0       467.0         3.3021        NEAR BAY  
28         1131.0       473.0         1.6424        NEAR BAY  
826         992.0       249.0         5.3644        NEAR BAY  
3735        862.0       368.0         3.6007       <1H OCEAN  
14946      1914.0       641.0         4.5135       <1H OCEAN  

[16512 rows x 9 columns]

In [5]:
y

7083     174400.0
747      135400.0
19922     94600.0
449      212000.0
11808    190500.0
           ...   
604      195700.0
28       108900.0
826      168800.0
3735     261800.0
14946    158300.0
Name: median_house_value, Length: 16512, dtype: float64

In [6]:
x_num 

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7083     -118.01     33.93                31.0       3395.0           742.0   
747      -122.09     37.66                40.0       1340.0           313.0   
19922    -119.35     36.32                10.0       3817.0           719.0   
449      -122.28     37.87                46.0       1777.0           446.0   
11808    -121.11     38.91                24.0       2558.0           423.0   
...          ...       ...                 ...          ...             ...   
604      -122.08     37.69                36.0       2350.0           499.0   
28       -122.28     37.84                50.0       2082.0           492.0   
826      -122.09     37.63                36.0       1570.0           274.0   
3735     -118.40     34.19                35.0       1631.0           356.0   
14946    -116.98     32.72                15.0       4209.0           680.0   

       population  households  median_income  
7083       1886.0       737.0         4.4118  
747         766.0       271.0         3.4722  
19922      1686.0       714.0         3.8235  
449         805.0       431.0         2.8676  
11808      1149.0       403.0         4.0679  
...           ...         ...            ...  
604        1105.0       467.0         3.3021  
28         1131.0       473.0         1.6424  
826         992.0       249.0         5.3644  
3735        862.0       368.0         3.6007  
14946      1914.0       641.0         4.5135  

[16512 rows x 8 columns]

### This class can add new columns

In [7]:
from sklearn.base import BaseEstimator, TransformerMixin
# we should columns indexs 
rooms_ix, bedrooms_ix, population_ix, households_ix = 3, 4, 5, 6

class CombineAttributesAdder(BaseEstimator, TransformerMixin):
  def __init__(self, add_bedrooms_per_room = False):
    self.add_bedrooms_per_room = add_bedrooms_per_room
  
  def fit(self, X, y = None):
    return self
  
  def transform(self, X):
    rooms_per_household = X[:, rooms_ix] / X[:, households_ix]
    population_per_household = X[:, population_ix] / X[:, households_ix]

    if self.add_bedrooms_per_room:
      bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
      return np.c_[X, rooms_per_household, population_per_household, bedrooms_per_room]
    else:
      return np.c_[X, rooms_per_household, population_per_household]

### Creat pip line

In [8]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

num_pipline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('atribut_adder', CombineAttributesAdder(add_bedrooms_per_room = True)),
    ('standart_scaler', StandardScaler())
])

num_pipline.fit_transform(dataset.drop('ocean_proximity', axis = 1).values)

array([[-1.32783522,  1.05254828,  0.98214266, ...,  0.62855945,
        -0.04959654, -1.02998783],
       [-1.32284391,  1.04318455, -0.60701891, ...,  0.32704136,
        -0.09251223, -0.8888972 ],
       [-1.33282653,  1.03850269,  1.85618152, ...,  1.15562047,
        -0.02584253, -1.29168566],
       ...,
       [-0.8237132 ,  1.77823747, -0.92485123, ..., -0.09031802,
        -0.0717345 ,  0.02113407],
       [-0.87362627,  1.77823747, -0.84539315, ..., -0.04021111,
        -0.09122515,  0.09346655],
       [-0.83369581,  1.75014627, -1.00430931, ..., -0.07044252,
        -0.04368215,  0.11327519]])

In [9]:
from sklearn.compose import ColumnTransformer

cat_attribs = ['ocean_proximity'] 
columns_num = list(x_num)

ful_pipline = ColumnTransformer([
    ('num', num_pipline, columns_num),
    ('cat', OneHotEncoder(), cat_attribs)
])

In [10]:
x_prepare = ful_pipline.fit_transform(x_train)
print(len(x_prepare))
x_prepare

16512


array([[ 0.77858458, -0.79543244,  0.18557923, ...,  0.        ,
         0.        ,  0.        ],
       [-1.26121131,  0.95153334,  0.89835081, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.10865162,  0.32393705, -1.47755446, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.26121131,  0.93748267,  0.58156344, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.58360409, -0.67366003,  0.5023666 , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.29353305, -1.36214252, -1.08157025, ...,  0.        ,
         0.        ,  0.        ]])

In [11]:
print(len(y))
y

16512


7083     174400.0
747      135400.0
19922     94600.0
449      212000.0
11808    190500.0
           ...   
604      195700.0
28       108900.0
826      168800.0
3735     261800.0
14946    158300.0
Name: median_house_value, Length: 16512, dtype: float64

### Fit the model

In [12]:
from sklearn.linear_model import  LinearRegression

model = LinearRegression()

In [13]:
model.fit(x_prepare, y);

### test the model

In [14]:
test_data = x_train.sample(10)
test_data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
17869    -121.91     37.44                24.0       1212.0           251.0   
3358     -120.66     40.41                52.0       2081.0           478.0   
13350    -117.63     34.02                13.0       4864.0           729.0   
5005     -118.32     34.01                50.0       1842.0           377.0   
14789    -117.13     32.58                27.0       1417.0           373.0   
4870     -118.28     34.03                40.0       2118.0           796.0   
5405     -118.44     34.03                37.0        975.0           189.0   
1777     -122.35     37.94                45.0       2112.0           493.0   
3233     -119.63     36.18                23.0        207.0            45.0   
15895    -122.40     37.73                48.0       1489.0           326.0   

       population  households  median_income ocean_proximity  
17869       799.0       242.0         5.0808       <1H OCEAN  
3358       1051.0       419.0         2.2992          INLAND  
13350      2780.0       723.0         5.6168          INLAND  
5005        817.0       341.0         3.1548       <1H OCEAN  
14789       814.0       348.0         2.3603      NEAR OCEAN  
4870       2195.0       658.0         1.7976       <1H OCEAN  
5405        489.0       202.0         4.2434       <1H OCEAN  
1777       1406.0       452.0         2.3456        NEAR BAY  
3233        171.0        50.0         2.4286          INLAND  
15895      1115.0       356.0         2.6364        NEAR BAY

In [15]:
test_lable = y.loc[test_data.index]
test_lable 

17869    212500.0
3358      70200.0
13350    175400.0
5005     157700.0
14789    195300.0
4870     164600.0
5405     331000.0
1777     105200.0
3233     100000.0
15895    199300.0
Name: median_house_value, dtype: float64

In [16]:
test_data = ful_pipline.transform(test_data)
test_data 

array([[-1.17122031e+00,  8.48495141e-01, -3.68798667e-01,
        -6.49284702e-01, -6.79096492e-01, -5.48635020e-01,
        -6.71857837e-01,  6.34307314e-01, -1.65856692e-01,
         1.72139343e-02, -1.01430193e-01,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-5.46282848e-01,  2.23951079e+00,  1.84871292e+00,
        -2.53297212e-01, -1.39877185e-01, -3.27908753e-01,
        -2.10166654e-01, -8.30420303e-01, -1.82154210e-01,
        -5.12488459e-02,  2.41449173e-01,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 9.68565568e-01, -7.53280455e-01, -1.23996393e+00,
         1.01486526e+00,  4.56352094e-01,  1.18651869e+00,
         5.82794475e-01,  9.16552786e-01,  5.06442921e-01,
         6.41132460e-02, -9.69478426e-01,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 6.23600087e-01, -7.57964009e

In [17]:
predict = model.predict(test_data)
predict

array([267474.21491669,  53626.28331233, 189028.72585682, 224236.56820007,
       183362.94652033, 165736.43935992, 246845.93107327, 183775.04522772,
        92830.3320447 , 199906.43486063])

In [18]:
test_lable

17869    212500.0
3358      70200.0
13350    175400.0
5005     157700.0
14789    195300.0
4870     164600.0
5405     331000.0
1777     105200.0
3233     100000.0
15895    199300.0
Name: median_house_value, dtype: float64

In [19]:
pd.DataFrame({'Bashorat' : predict, 'real value' : test_lable})

Bashorat  real value
17869  267474.214917    212500.0
3358    53626.283312     70200.0
13350  189028.725857    175400.0
5005   224236.568200    157700.0
14789  183362.946520    195300.0
4870   165736.439360    164600.0
5405   246845.931073    331000.0
1777   183775.045228    105200.0
3233    92830.332045    100000.0
15895  199906.434861    199300.0

## 5-QADAM. Modelni baholash
### 26.05.2023

In [20]:
test_set 

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
15430    -117.24     33.20                25.0       1631.0           415.0   
10950    -117.86     33.75                39.0        275.0            87.0   
14574    -117.22     32.82                22.0       3738.0           795.0   
9603     -120.49     37.30                50.0        985.0           309.0   
6005     -117.77     34.07                29.0       2976.0           662.0   
...          ...       ...                 ...          ...             ...   
4893     -118.25     34.02                32.0       1311.0           410.0   
7691     -118.11     33.95                34.0       2319.0           334.0   
11863    -121.24     40.31                36.0       1597.0           301.0   
17470    -119.81     34.47                26.0       4382.0           618.0   
9502     -123.54     39.17                18.0       2251.0           510.0   

       population  households  median_income  median_house_value  \
15430      1045.0       386.0         2.4505            147500.0   
10950       554.0       103.0         3.5972            158000.0   
14574      1476.0       728.0         3.7963            303100.0   
9603        621.0       250.0         1.3125             60900.0   
6005       2452.0       633.0         3.0638            113600.0   
...           ...         ...            ...                 ...   
4893       1792.0       396.0         2.3304            119900.0   
7691        941.0       356.0         6.4319            452300.0   
11863       632.0       262.0         3.5962             93600.0   
17470      1728.0       587.0         7.4734            432200.0   
9502       1032.0       369.0         2.2946            101000.0   

      ocean_proximity  
15430       <1H OCEAN  
10950       <1H OCEAN  
14574      NEAR OCEAN  
9603           INLAND  
6005           INLAND  
...               ...  
4893        <1H OCEAN  
7691        <1H OCEAN  
11863          INLAND  
17470      NEAR OCEAN  
9502        <1H OCEAN  

[4128 rows x 10 columns]

In [21]:
x_test = test_set.drop('median_house_value', axis = 1)
x_test

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
15430    -117.24     33.20                25.0       1631.0           415.0   
10950    -117.86     33.75                39.0        275.0            87.0   
14574    -117.22     32.82                22.0       3738.0           795.0   
9603     -120.49     37.30                50.0        985.0           309.0   
6005     -117.77     34.07                29.0       2976.0           662.0   
...          ...       ...                 ...          ...             ...   
4893     -118.25     34.02                32.0       1311.0           410.0   
7691     -118.11     33.95                34.0       2319.0           334.0   
11863    -121.24     40.31                36.0       1597.0           301.0   
17470    -119.81     34.47                26.0       4382.0           618.0   
9502     -123.54     39.17                18.0       2251.0           510.0   

       population  households  median_income ocean_proximity  
15430      1045.0       386.0         2.4505       <1H OCEAN  
10950       554.0       103.0         3.5972       <1H OCEAN  
14574      1476.0       728.0         3.7963      NEAR OCEAN  
9603        621.0       250.0         1.3125          INLAND  
6005       2452.0       633.0         3.0638          INLAND  
...           ...         ...            ...             ...  
4893       1792.0       396.0         2.3304       <1H OCEAN  
7691        941.0       356.0         6.4319       <1H OCEAN  
11863       632.0       262.0         3.5962          INLAND  
17470      1728.0       587.0         7.4734      NEAR OCEAN  
9502       1032.0       369.0         2.2946       <1H OCEAN  

[4128 rows x 9 columns]

In [22]:
y_test = test_set['median_house_value'].copy()
y_test

15430    147500.0
10950    158000.0
14574    303100.0
9603      60900.0
6005     113600.0
           ...   
4893     119900.0
7691     452300.0
11863     93600.0
17470    432200.0
9502     101000.0
Name: median_house_value, Length: 4128, dtype: float64

In [23]:
x_test_prepare = ful_pipline.transform(x_test)
y_predict = model.predict(x_test_prepare)

In [24]:
y_predict

array([162030.0233051 , 211170.48710141, 250213.99180113, ...,
        98840.13741573, 392850.74323332, 166448.2336177 ])