<a href="https://colab.research.google.com/github/SHermukhammadjon/Data_Science_Zero_to_Mastery/blob/main/scikit_learn2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn

# 3-QADAM. MLga tayyorgarlik. NaN qiymatlar.
###13.05.2023

In [3]:
def load_dataset(URL):
  return pd.read_csv(URL)

In [9]:
dataset = load_dataset("https://github.com/ageron/handson-ml2/blob/master/datasets/housing/housing.csv?raw=true")
dataset.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [10]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(dataset, test_size = 0.2, random_state = 31)

In [15]:
housing = train_set.drop('median_house_value', axis = 1)
housing_lables = train_set['median_house_value'].copy()

In [16]:
housing

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7083     -118.01     33.93                31.0       3395.0           742.0   
747      -122.09     37.66                40.0       1340.0           313.0   
19922    -119.35     36.32                10.0       3817.0           719.0   
449      -122.28     37.87                46.0       1777.0           446.0   
11808    -121.11     38.91                24.0       2558.0           423.0   
...          ...       ...                 ...          ...             ...   
604      -122.08     37.69                36.0       2350.0           499.0   
28       -122.28     37.84                50.0       2082.0           492.0   
826      -122.09     37.63                36.0       1570.0           274.0   
3735     -118.40     34.19                35.0       1631.0           356.0   
14946    -116.98     32.72                15.0       4209.0           680.0   

       population  households  median_income ocean_proximity  
7083       1886.0       737.0         4.4118       <1H OCEAN  
747         766.0       271.0         3.4722        NEAR BAY  
19922      1686.0       714.0         3.8235          INLAND  
449         805.0       431.0         2.8676        NEAR BAY  
11808      1149.0       403.0         4.0679          INLAND  
...           ...         ...            ...             ...  
604        1105.0       467.0         3.3021        NEAR BAY  
28         1131.0       473.0         1.6424        NEAR BAY  
826         992.0       249.0         5.3644        NEAR BAY  
3735        862.0       368.0         3.6007       <1H OCEAN  
14946      1914.0       641.0         4.5135       <1H OCEAN  

[16512 rows x 9 columns]

In [18]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16512 entries, 7083 to 14946
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           16512 non-null  float64
 1   latitude            16512 non-null  float64
 2   housing_median_age  16512 non-null  float64
 3   total_rooms         16512 non-null  float64
 4   total_bedrooms      16347 non-null  float64
 5   population          16512 non-null  float64
 6   households          16512 non-null  float64
 7   median_income       16512 non-null  float64
 8   ocean_proximity     16512 non-null  object 
dtypes: float64(8), object(1)
memory usage: 1.3+ MB


In [20]:
# 1 Qatorlarni tashlab yuborish
housing.dropna(subset = ['total_bedrooms'])

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7083     -118.01     33.93                31.0       3395.0           742.0   
747      -122.09     37.66                40.0       1340.0           313.0   
19922    -119.35     36.32                10.0       3817.0           719.0   
449      -122.28     37.87                46.0       1777.0           446.0   
11808    -121.11     38.91                24.0       2558.0           423.0   
...          ...       ...                 ...          ...             ...   
604      -122.08     37.69                36.0       2350.0           499.0   
28       -122.28     37.84                50.0       2082.0           492.0   
826      -122.09     37.63                36.0       1570.0           274.0   
3735     -118.40     34.19                35.0       1631.0           356.0   
14946    -116.98     32.72                15.0       4209.0           680.0   

       population  households  median_income ocean_proximity  
7083       1886.0       737.0         4.4118       <1H OCEAN  
747         766.0       271.0         3.4722        NEAR BAY  
19922      1686.0       714.0         3.8235          INLAND  
449         805.0       431.0         2.8676        NEAR BAY  
11808      1149.0       403.0         4.0679          INLAND  
...           ...         ...            ...             ...  
604        1105.0       467.0         3.3021        NEAR BAY  
28         1131.0       473.0         1.6424        NEAR BAY  
826         992.0       249.0         5.3644        NEAR BAY  
3735        862.0       368.0         3.6007       <1H OCEAN  
14946      1914.0       641.0         4.5135       <1H OCEAN  

[16347 rows x 9 columns]

In [27]:
median = housing['total_bedrooms'].median()
median

433.0

In [29]:
housing['total_bedrooms'].fillna(median, inplace = True)

In [31]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16512 entries, 7083 to 14946
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           16512 non-null  float64
 1   latitude            16512 non-null  float64
 2   housing_median_age  16512 non-null  float64
 3   total_rooms         16512 non-null  float64
 4   total_bedrooms      16512 non-null  float64
 5   population          16512 non-null  float64
 6   households          16512 non-null  float64
 7   median_income       16512 non-null  float64
 8   ocean_proximity     16512 non-null  object 
dtypes: float64(8), object(1)
memory usage: 1.3+ MB


# 3-QADAM. MLga tayyorgarlik. NaN qiymatlarni almashtirish
### 13.05.2023

#### SimpleImputer

In [33]:
from sklearn.impute import SimpleImputer

In [45]:
imputer = SimpleImputer(strategy = 'median')

In [36]:
housing_num = housing.drop('ocean_proximity', axis = 1)
housing_num 

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7083     -118.01     33.93                31.0       3395.0           742.0   
747      -122.09     37.66                40.0       1340.0           313.0   
19922    -119.35     36.32                10.0       3817.0           719.0   
449      -122.28     37.87                46.0       1777.0           446.0   
11808    -121.11     38.91                24.0       2558.0           423.0   
...          ...       ...                 ...          ...             ...   
604      -122.08     37.69                36.0       2350.0           499.0   
28       -122.28     37.84                50.0       2082.0           492.0   
826      -122.09     37.63                36.0       1570.0           274.0   
3735     -118.40     34.19                35.0       1631.0           356.0   
14946    -116.98     32.72                15.0       4209.0           680.0   

       population  households  median_income  
7083       1886.0       737.0         4.4118  
747         766.0       271.0         3.4722  
19922      1686.0       714.0         3.8235  
449         805.0       431.0         2.8676  
11808      1149.0       403.0         4.0679  
...           ...         ...            ...  
604        1105.0       467.0         3.3021  
28         1131.0       473.0         1.6424  
826         992.0       249.0         5.3644  
3735        862.0       368.0         3.6007  
14946      1914.0       641.0         4.5135  

[16512 rows x 8 columns]

In [47]:
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [43]:
imputer.statistics_ # Harbir ustun uchun median qiyamat

array([-118.5   ,   34.26  ,   29.    , 2127.    ,  433.    , 1166.    ,
        408.    ,    3.5394])

In [49]:
X = imputer.transform(housing_num)
X

array([[-118.01  ,   33.93  ,   31.    , ..., 1886.    ,  737.    ,
           4.4118],
       [-122.09  ,   37.66  ,   40.    , ...,  766.    ,  271.    ,
           3.4722],
       [-119.35  ,   36.32  ,   10.    , ..., 1686.    ,  714.    ,
           3.8235],
       ...,
       [-122.09  ,   37.63  ,   36.    , ...,  992.    ,  249.    ,
           5.3644],
       [-118.4   ,   34.19  ,   35.    , ...,  862.    ,  368.    ,
           3.6007],
       [-116.98  ,   32.72  ,   15.    , ..., 1914.    ,  641.    ,
           4.5135]])

In [50]:
type(X)

numpy.ndarray

In [51]:
imputer.fit_transform(housing_num)

array([[-118.01  ,   33.93  ,   31.    , ..., 1886.    ,  737.    ,
           4.4118],
       [-122.09  ,   37.66  ,   40.    , ...,  766.    ,  271.    ,
           3.4722],
       [-119.35  ,   36.32  ,   10.    , ..., 1686.    ,  714.    ,
           3.8235],
       ...,
       [-122.09  ,   37.63  ,   36.    , ...,  992.    ,  249.    ,
           5.3644],
       [-118.4   ,   34.19  ,   35.    , ...,  862.    ,  368.    ,
           3.6007],
       [-116.98  ,   32.72  ,   15.    , ..., 1914.    ,  641.    ,
           4.5135]])

In [52]:
housing_tr = pd.DataFrame(X, columns = housing_num.columns, index = housing_num.index)
housing_tr

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7083     -118.01     33.93                31.0       3395.0           742.0   
747      -122.09     37.66                40.0       1340.0           313.0   
19922    -119.35     36.32                10.0       3817.0           719.0   
449      -122.28     37.87                46.0       1777.0           446.0   
11808    -121.11     38.91                24.0       2558.0           423.0   
...          ...       ...                 ...          ...             ...   
604      -122.08     37.69                36.0       2350.0           499.0   
28       -122.28     37.84                50.0       2082.0           492.0   
826      -122.09     37.63                36.0       1570.0           274.0   
3735     -118.40     34.19                35.0       1631.0           356.0   
14946    -116.98     32.72                15.0       4209.0           680.0   

       population  households  median_income  
7083       1886.0       737.0         4.4118  
747         766.0       271.0         3.4722  
19922      1686.0       714.0         3.8235  
449         805.0       431.0         2.8676  
11808      1149.0       403.0         4.0679  
...           ...         ...            ...  
604        1105.0       467.0         3.3021  
28         1131.0       473.0         1.6424  
826         992.0       249.0         5.3644  
3735        862.0       368.0         3.6007  
14946      1914.0       641.0         4.5135  

[16512 rows x 8 columns]

# 3-QADAM. MLga tayyorgarlik. Matnlar. SimpleEncoder

In [68]:
housing_cat = housing[['ocean_proximity']]
housing_cat

ocean_proximity
7083        <1H OCEAN
747          NEAR BAY
19922          INLAND
449          NEAR BAY
11808          INLAND
...               ...
604          NEAR BAY
28           NEAR BAY
826          NEAR BAY
3735        <1H OCEAN
14946       <1H OCEAN

[16512 rows x 1 columns]

In [56]:
housing_cat.value_counts()

<1H OCEAN     7318
INLAND        5225
NEAR OCEAN    2107
NEAR BAY      1857
ISLAND           5
Name: ocean_proximity, dtype: int64

In [59]:
from sklearn.preprocessing import OrdinalEncoder

In [61]:
encoder = OrdinalEncoder()

In [70]:
housing_cat_encoder = encoder.fit_transform(housing_cat)
housing_cat_encoder

array([[0.],
       [3.],
       [1.],
       ...,
       [3.],
       [0.],
       [0.]])

In [72]:
housing_cat_encoder

array([[0.],
       [3.],
       [1.],
       ...,
       [3.],
       [0.],
       [0.]])