<a href="https://colab.research.google.com/github/SHermukhammadjon/Data_Science_Zero_to_Mastery/blob/main/NumPy/introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np

### Anatomy of a NumPy array:

<img src='https://drive.google.com/uc?id=1qEA5LXtXOiOICMeH5yji93avRPvN6dNw'>

# DataTypes & Attributes

In [23]:
# NumPy's main dataype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [24]:
type(a1)

numpy.ndarray

In [28]:
a2 = np.array([[1, 2, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])

In [31]:
a2 

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [33]:
a3 

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [35]:
a1.shape

(3,)

In [36]:
a2.shape

(2, 3)

In [37]:
a3.shape

(2, 3, 3)

In [40]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [41]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [42]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [43]:
type(a1), type(a2), type(a2)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [45]:
# Create a DatFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# Creating NumPy arrays

In [47]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [48]:
sample_array.dtype

dtype('int64')

In [54]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
type(ones)

numpy.ndarray

In [58]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
type(zeros)

numpy.ndarray

In [62]:
range_array = np.arange(0, 10, 2)
range_array 

array([0, 2, 4, 6, 8])

In [63]:
random_array = np.random.randint(0, 10, size = (3, 5))
random_array

array([[6, 7, 8, 0, 0],
       [6, 4, 7, 3, 8],
       [5, 1, 7, 4, 4]])

In [72]:
random_array_2 = np.random.random([5, 3])
random_array_2

array([[0.79322286, 0.85386565, 0.89310808],
       [0.09303118, 0.03781699, 0.40795525],
       [0.76545617, 0.12748831, 0.86480767],
       [0.35770061, 0.57873403, 0.98067904],
       [0.90213185, 0.65033381, 0.15773639]])

In [69]:
random_array_2.shape

(5, 3)

In [71]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.83455675, 0.20455741, 0.57782904],
       [0.5674388 , 0.40654137, 0.1725303 ],
       [0.88711343, 0.8836835 , 0.20579672],
       [0.21480187, 0.5793914 , 0.41450809],
       [0.25559352, 0.25685672, 0.41838436]])

In [79]:
# Pseudo-random numbers
np.random.seed()